### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gsathya** [gsathya/blocker#1]
- [ ] Figure out deployment with ansible
- [ ] Figure out how to send data back
- [ ] NAT traversal
- [ ] Create package for openwrt
- [ ] Fix Android build
